[package]
name = "ori-native-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
layer-shell = []

[dependencies]
ori   = { workspace = true }
taffy = { workspace = true }
